### ISSUE TITLE
Want to add a complete explanation for Sliding Window Technique.

### ISSUE THREAD

**Issue by KrishJani** [aniruddhabagal/DSA-Practice#5]
I see you have taken a nice initiative of making a GitHub repo with important DSA concepts.
I want to contribute to this and add one more very important concept of the sliding window.

It will contain...

- [X] Explanation of the concept
- [X] Code templet
- [X] List of example problems
- [X] Also a list of problems that people misunderstand as the sliding window technique but actually they are not.

Kindly assign me to this and put a hacktoberfest tag to it.

**Comment by aniruddhabagal** [comment]
okay. You can go ahead!

**Comment by aniruddhabagal** [comment]
Just see to it that you upload the files in separate folder named "Sliding Window" and create a pr

**Comment by KrishJani** [comment]
> Just see to it that you upload the files in separate folder named "Sliding Window" and create a pr

Okay.
